### ISSUE TITLE
Make translateable error message

### ISSUE THREAD

**Issue by ruthgeridema** [MultiSafepay/magento2-frontend#10]
https://github.com/MultiSafepay/magento2-frontend/blob/master/Controller/Connect/Redirect.php:95

Please make this one translatable!
Thanks :)

**Comment by vinodsowdagar** [comment]
Hi @ruthgeridema ,

Thank you for addressing this issue.
Nice catch, the change will be released in the next version.

We will keep you informed of the release.

**Comment by vinodsowdagar** [comment]
Hi @ruthgeridema ,

We've added your suggested change in the latest version of the module: https://github.com/MultiSafepay/magento2/releases/tag/3.5.0

For now I am closing this issue, if there are any questions or comments, feel free to place them here and we can consider reopening this issue.
